package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * ClassesId generated by hbm2java
 */
public class ClassesId  implements java.io.Serializable {


     private int no;
     private String studentId;
     private String fullname;
     private String gender;
     private String cardId;
     private String subjectId;

    public ClassesId() {
    }

	
    public ClassesId(int no) {
        this.no = no;
    }
    public ClassesId(int no, String studentId, String fullname, String gender, String cardId, String subjectId) {
       this.no = no;
       this.studentId = studentId;
       this.fullname = fullname;
       this.gender = gender;
       this.cardId = cardId;
       this.subjectId = subjectId;
    }
   
    public int getNo() {
        return this.no;
    }
    
    public void setNo(int no) {
        this.no = no;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getCardId() {
        return this.cardId;
    }
    
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClassesId) ) return false;
		 ClassesId castOther = ( ClassesId ) other; 
         
		 return (this.getNo()==castOther.getNo())
 && ( (this.getStudentId()==castOther.getStudentId()) || ( this.getStudentId()!=null && castOther.getStudentId()!=null && this.getStudentId().equals(castOther.getStudentId()) ) )
 && ( (this.getFullname()==castOther.getFullname()) || ( this.getFullname()!=null && castOther.getFullname()!=null && this.getFullname().equals(castOther.getFullname()) ) )
 && ( (this.getGender()==castOther.getGender()) || ( this.getGender()!=null && castOther.getGender()!=null && this.getGender().equals(castOther.getGender()) ) )
 && ( (this.getCardId()==castOther.getCardId()) || ( this.getCardId()!=null && castOther.getCardId()!=null && this.getCardId().equals(castOther.getCardId()) ) )
 && ( (this.getSubjectId()==castOther.getSubjectId()) || ( this.getSubjectId()!=null && castOther.getSubjectId()!=null && this.getSubjectId().equals(castOther.getSubjectId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNo();
         result = 37 * result + ( getStudentId() == null ? 0 : this.getStudentId().hashCode() );
         result = 37 * result + ( getFullname() == null ? 0 : this.getFullname().hashCode() );
         result = 37 * result + ( getGender() == null ? 0 : this.getGender().hashCode() );
         result = 37 * result + ( getCardId() == null ? 0 : this.getCardId().hashCode() );
         result = 37 * result + ( getSubjectId() == null ? 0 : this.getSubjectId().hashCode() );
         return result;
   }   


}


