package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * Classes generated by hbm2java
 */
public class Classes  implements java.io.Serializable {


     private ClassesId id;

    public Classes() {
    }

    public Classes(ClassesId id) {
       this.id = id;
    }
   
    public ClassesId getId() {
        return this.id;
    }
    
    public void setId(ClassesId id) {
        this.id = id;
    }




}


