package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * Remarking generated by hbm2java
 */
public class Remarking  implements java.io.Serializable {


     private RemarkingId id;

    public Remarking() {
    }

    public Remarking(RemarkingId id) {
       this.id = id;
    }
   
    public RemarkingId getId() {
        return this.id;
    }
    
    public void setId(RemarkingId id) {
        this.id = id;
    }




}


