package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * Remarkid generated by hbm2java
 */
public class Remarkid  implements java.io.Serializable {


     private RemarkidId id;

    public Remarkid() {
    }

    public Remarkid(RemarkidId id) {
       this.id = id;
    }
   
    public RemarkidId getId() {
        return this.id;
    }
    
    public void setId(RemarkidId id) {
        this.id = id;
    }




}


