package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * RemarkingId generated by hbm2java
 */
public class RemarkingId  implements java.io.Serializable {


     private int no;
     private String remarkId;
     private String studentId;
     private String fullname;
     private String subject;
     private String colExam;
     private Float mark;
     private String reason;
     private String status;

    public RemarkingId() {
    }

	
    public RemarkingId(int no) {
        this.no = no;
    }
    public RemarkingId(int no, String remarkId, String studentId, String fullname, String subject, String colExam, Float mark, String reason, String status) {
       this.no = no;
       this.remarkId = remarkId;
       this.studentId = studentId;
       this.fullname = fullname;
       this.subject = subject;
       this.colExam = colExam;
       this.mark = mark;
       this.reason = reason;
       this.status = status;
    }
   
    public int getNo() {
        return this.no;
    }
    
    public void setNo(int no) {
        this.no = no;
    }
    public String getRemarkId() {
        return this.remarkId;
    }
    
    public void setRemarkId(String remarkId) {
        this.remarkId = remarkId;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getColExam() {
        return this.colExam;
    }
    
    public void setColExam(String colExam) {
        this.colExam = colExam;
    }
    public Float getMark() {
        return this.mark;
    }
    
    public void setMark(Float mark) {
        this.mark = mark;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RemarkingId) ) return false;
		 RemarkingId castOther = ( RemarkingId ) other; 
         
		 return (this.getNo()==castOther.getNo())
 && ( (this.getRemarkId()==castOther.getRemarkId()) || ( this.getRemarkId()!=null && castOther.getRemarkId()!=null && this.getRemarkId().equals(castOther.getRemarkId()) ) )
 && ( (this.getStudentId()==castOther.getStudentId()) || ( this.getStudentId()!=null && castOther.getStudentId()!=null && this.getStudentId().equals(castOther.getStudentId()) ) )
 && ( (this.getFullname()==castOther.getFullname()) || ( this.getFullname()!=null && castOther.getFullname()!=null && this.getFullname().equals(castOther.getFullname()) ) )
 && ( (this.getSubject()==castOther.getSubject()) || ( this.getSubject()!=null && castOther.getSubject()!=null && this.getSubject().equals(castOther.getSubject()) ) )
 && ( (this.getColExam()==castOther.getColExam()) || ( this.getColExam()!=null && castOther.getColExam()!=null && this.getColExam().equals(castOther.getColExam()) ) )
 && ( (this.getMark()==castOther.getMark()) || ( this.getMark()!=null && castOther.getMark()!=null && this.getMark().equals(castOther.getMark()) ) )
 && ( (this.getReason()==castOther.getReason()) || ( this.getReason()!=null && castOther.getReason()!=null && this.getReason().equals(castOther.getReason()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNo();
         result = 37 * result + ( getRemarkId() == null ? 0 : this.getRemarkId().hashCode() );
         result = 37 * result + ( getStudentId() == null ? 0 : this.getStudentId().hashCode() );
         result = 37 * result + ( getFullname() == null ? 0 : this.getFullname().hashCode() );
         result = 37 * result + ( getSubject() == null ? 0 : this.getSubject().hashCode() );
         result = 37 * result + ( getColExam() == null ? 0 : this.getColExam().hashCode() );
         result = 37 * result + ( getMark() == null ? 0 : this.getMark().hashCode() );
         result = 37 * result + ( getReason() == null ? 0 : this.getReason().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         return result;
   }   


}


