package Model;
// Generated Jun 15, 2020 12:25:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Remarkid generated by hbm2java
 */
public class Remarkid  implements java.io.Serializable {


     private Integer no;
     private String name;
     private Date dateFrom;
     private Date dateTo;

    public Remarkid() {
    }

    public Remarkid(String name, Date dateFrom, Date dateTo) {
       this.name = name;
       this.dateFrom = dateFrom;
       this.dateTo = dateTo;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateFrom() {
        return this.dateFrom;
    }
    
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }
    public Date getDateTo() {
        return this.dateTo;
    }
    
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }




}


