package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * ScoreId generated by hbm2java
 */
public class ScoreId  implements java.io.Serializable {


     private int no;
     private String studentId;
     private String fullname;
     private String middleExam;
     private Float finalExam;
     private Float plusExam;
     private Float avgScore;
     private String subjectId;

    public ScoreId() {
    }

	
    public ScoreId(int no) {
        this.no = no;
    }
    public ScoreId(int no, String studentId, String fullname, String middleExam, Float finalExam, Float plusExam, Float avgScore, String subjectId) {
       this.no = no;
       this.studentId = studentId;
       this.fullname = fullname;
       this.middleExam = middleExam;
       this.finalExam = finalExam;
       this.plusExam = plusExam;
       this.avgScore = avgScore;
       this.subjectId = subjectId;
    }
   
    public int getNo() {
        return this.no;
    }
    
    public void setNo(int no) {
        this.no = no;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getMiddleExam() {
        return this.middleExam;
    }
    
    public void setMiddleExam(String middleExam) {
        this.middleExam = middleExam;
    }
    public Float getFinalExam() {
        return this.finalExam;
    }
    
    public void setFinalExam(Float finalExam) {
        this.finalExam = finalExam;
    }
    public Float getPlusExam() {
        return this.plusExam;
    }
    
    public void setPlusExam(Float plusExam) {
        this.plusExam = plusExam;
    }
    public Float getAvgScore() {
        return this.avgScore;
    }
    
    public void setAvgScore(Float avgScore) {
        this.avgScore = avgScore;
    }
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScoreId) ) return false;
		 ScoreId castOther = ( ScoreId ) other; 
         
		 return (this.getNo()==castOther.getNo())
 && ( (this.getStudentId()==castOther.getStudentId()) || ( this.getStudentId()!=null && castOther.getStudentId()!=null && this.getStudentId().equals(castOther.getStudentId()) ) )
 && ( (this.getFullname()==castOther.getFullname()) || ( this.getFullname()!=null && castOther.getFullname()!=null && this.getFullname().equals(castOther.getFullname()) ) )
 && ( (this.getMiddleExam()==castOther.getMiddleExam()) || ( this.getMiddleExam()!=null && castOther.getMiddleExam()!=null && this.getMiddleExam().equals(castOther.getMiddleExam()) ) )
 && ( (this.getFinalExam()==castOther.getFinalExam()) || ( this.getFinalExam()!=null && castOther.getFinalExam()!=null && this.getFinalExam().equals(castOther.getFinalExam()) ) )
 && ( (this.getPlusExam()==castOther.getPlusExam()) || ( this.getPlusExam()!=null && castOther.getPlusExam()!=null && this.getPlusExam().equals(castOther.getPlusExam()) ) )
 && ( (this.getAvgScore()==castOther.getAvgScore()) || ( this.getAvgScore()!=null && castOther.getAvgScore()!=null && this.getAvgScore().equals(castOther.getAvgScore()) ) )
 && ( (this.getSubjectId()==castOther.getSubjectId()) || ( this.getSubjectId()!=null && castOther.getSubjectId()!=null && this.getSubjectId().equals(castOther.getSubjectId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNo();
         result = 37 * result + ( getStudentId() == null ? 0 : this.getStudentId().hashCode() );
         result = 37 * result + ( getFullname() == null ? 0 : this.getFullname().hashCode() );
         result = 37 * result + ( getMiddleExam() == null ? 0 : this.getMiddleExam().hashCode() );
         result = 37 * result + ( getFinalExam() == null ? 0 : this.getFinalExam().hashCode() );
         result = 37 * result + ( getPlusExam() == null ? 0 : this.getPlusExam().hashCode() );
         result = 37 * result + ( getAvgScore() == null ? 0 : this.getAvgScore().hashCode() );
         result = 37 * result + ( getSubjectId() == null ? 0 : this.getSubjectId().hashCode() );
         return result;
   }   


}


