package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * Score generated by hbm2java
 */
public class Score  implements java.io.Serializable {


     private ScoreId id;

    public Score() {
    }

    public Score(ScoreId id) {
       this.id = id;
    }
   
    public ScoreId getId() {
        return this.id;
    }
    
    public void setId(ScoreId id) {
        this.id = id;
    }




}


