package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private StudentId id;

    public Student() {
    }

    public Student(StudentId id) {
       this.id = id;
    }
   
    public StudentId getId() {
        return this.id;
    }
    
    public void setId(StudentId id) {
        this.id = id;
    }




}


