package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * StudentId generated by hbm2java
 */
public class StudentId  implements java.io.Serializable {


     private int no;
     private String studentId;
     private String fullname;
     private String gender;
     private String idcard;
     private String classes;

    public StudentId() {
    }

	
    public StudentId(int no) {
        this.no = no;
    }
    public StudentId(int no, String studentId, String fullname, String gender, String idcard, String classes) {
       this.no = no;
       this.studentId = studentId;
       this.fullname = fullname;
       this.gender = gender;
       this.idcard = idcard;
       this.classes = classes;
    }
   
    public int getNo() {
        return this.no;
    }
    
    public void setNo(int no) {
        this.no = no;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getIdcard() {
        return this.idcard;
    }
    
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }
    public String getClasses() {
        return this.classes;
    }
    
    public void setClasses(String classes) {
        this.classes = classes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentId) ) return false;
		 StudentId castOther = ( StudentId ) other; 
         
		 return (this.getNo()==castOther.getNo())
 && ( (this.getStudentId()==castOther.getStudentId()) || ( this.getStudentId()!=null && castOther.getStudentId()!=null && this.getStudentId().equals(castOther.getStudentId()) ) )
 && ( (this.getFullname()==castOther.getFullname()) || ( this.getFullname()!=null && castOther.getFullname()!=null && this.getFullname().equals(castOther.getFullname()) ) )
 && ( (this.getGender()==castOther.getGender()) || ( this.getGender()!=null && castOther.getGender()!=null && this.getGender().equals(castOther.getGender()) ) )
 && ( (this.getIdcard()==castOther.getIdcard()) || ( this.getIdcard()!=null && castOther.getIdcard()!=null && this.getIdcard().equals(castOther.getIdcard()) ) )
 && ( (this.getClasses()==castOther.getClasses()) || ( this.getClasses()!=null && castOther.getClasses()!=null && this.getClasses().equals(castOther.getClasses()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNo();
         result = 37 * result + ( getStudentId() == null ? 0 : this.getStudentId().hashCode() );
         result = 37 * result + ( getFullname() == null ? 0 : this.getFullname().hashCode() );
         result = 37 * result + ( getGender() == null ? 0 : this.getGender().hashCode() );
         result = 37 * result + ( getIdcard() == null ? 0 : this.getIdcard().hashCode() );
         result = 37 * result + ( getClasses() == null ? 0 : this.getClasses().hashCode() );
         return result;
   }   


}


