package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private SubjectId id;

    public Subject() {
    }

    public Subject(SubjectId id) {
       this.id = id;
    }
   
    public SubjectId getId() {
        return this.id;
    }
    
    public void setId(SubjectId id) {
        this.id = id;
    }




}


