package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * Timetable generated by hbm2java
 */
public class Timetable  implements java.io.Serializable {


     private TimetableId id;

    public Timetable() {
    }

    public Timetable(TimetableId id) {
       this.id = id;
    }
   
    public TimetableId getId() {
        return this.id;
    }
    
    public void setId(TimetableId id) {
        this.id = id;
    }




}


