package Model;
// Generated Jun 13, 2020 12:13:38 AM by Hibernate Tools 4.3.1



/**
 * TimetableId generated by hbm2java
 */
public class TimetableId  implements java.io.Serializable {


     private int no;
     private Integer subjectId;
     private String subjectName;
     private Integer room;
     private Integer classId;
     private Integer studentId;

    public TimetableId() {
    }

	
    public TimetableId(int no) {
        this.no = no;
    }
    public TimetableId(int no, Integer subjectId, String subjectName, Integer room, Integer classId, Integer studentId) {
       this.no = no;
       this.subjectId = subjectId;
       this.subjectName = subjectName;
       this.room = room;
       this.classId = classId;
       this.studentId = studentId;
    }
   
    public int getNo() {
        return this.no;
    }
    
    public void setNo(int no) {
        this.no = no;
    }
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public Integer getRoom() {
        return this.room;
    }
    
    public void setRoom(Integer room) {
        this.room = room;
    }
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TimetableId) ) return false;
		 TimetableId castOther = ( TimetableId ) other; 
         
		 return (this.getNo()==castOther.getNo())
 && ( (this.getSubjectId()==castOther.getSubjectId()) || ( this.getSubjectId()!=null && castOther.getSubjectId()!=null && this.getSubjectId().equals(castOther.getSubjectId()) ) )
 && ( (this.getSubjectName()==castOther.getSubjectName()) || ( this.getSubjectName()!=null && castOther.getSubjectName()!=null && this.getSubjectName().equals(castOther.getSubjectName()) ) )
 && ( (this.getRoom()==castOther.getRoom()) || ( this.getRoom()!=null && castOther.getRoom()!=null && this.getRoom().equals(castOther.getRoom()) ) )
 && ( (this.getClassId()==castOther.getClassId()) || ( this.getClassId()!=null && castOther.getClassId()!=null && this.getClassId().equals(castOther.getClassId()) ) )
 && ( (this.getStudentId()==castOther.getStudentId()) || ( this.getStudentId()!=null && castOther.getStudentId()!=null && this.getStudentId().equals(castOther.getStudentId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNo();
         result = 37 * result + ( getSubjectId() == null ? 0 : this.getSubjectId().hashCode() );
         result = 37 * result + ( getSubjectName() == null ? 0 : this.getSubjectName().hashCode() );
         result = 37 * result + ( getRoom() == null ? 0 : this.getRoom().hashCode() );
         result = 37 * result + ( getClassId() == null ? 0 : this.getClassId().hashCode() );
         result = 37 * result + ( getStudentId() == null ? 0 : this.getStudentId().hashCode() );
         return result;
   }   


}


