/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DAO.AccountDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author coluc
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel_Username1 = new javax.swing.JLabel();
        cmbPermit = new javax.swing.JComboBox<>();
        jlabel_Username = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jlabel_Password2 = new javax.swing.JLabel();
        jlabel_Password3 = new javax.swing.JLabel();
        txtCurrent = new javax.swing.JPasswordField();
        jlabel_Password1 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JPasswordField();
        jlabel_Password = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();
        jbtnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabel_Username1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel_Username1.setText("Phân quyền");
        jlabel_Username1.setToolTipText("");

        cmbPermit.setEditable(true);
        cmbPermit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbPermit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher" }));
        cmbPermit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPermitActionPerformed(evt);
            }
        });

        jlabel_Username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel_Username.setText("Tên đăng nhập ");
        jlabel_Username.setToolTipText("");

        txtUsername.setFocusCycleRoot(true);

        jlabel_Password2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel_Password2.setToolTipText("");

        jlabel_Password3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel_Password3.setText("Mật khẩu cũ");
        jlabel_Password3.setToolTipText("");

        txtCurrent.setToolTipText("");

        jlabel_Password1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel_Password1.setText("Mật khẩu mới");
        jlabel_Password1.setToolTipText("");

        txtPassword1.setToolTipText("");

        jlabel_Password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel_Password.setText("Nhập lại mật khẩu");
        jlabel_Password.setToolTipText("");

        txtPassword2.setToolTipText("");

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnLogin.setText("apply ");
        jbtnLogin.setName("Login"); // NOI18N
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setText("cancel");
        btnCancel.setName("Login"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jlabel_Password2)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabel_Password1)
                            .addComponent(jlabel_Password3)
                            .addComponent(jlabel_Username)
                            .addComponent(jlabel_Username1)
                            .addComponent(jlabel_Password))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbPermit, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addComponent(txtCurrent)
                        .addComponent(txtPassword1))
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPermit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_Username1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_Username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabel_Password3)
                    .addComponent(txtCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jlabel_Password2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel_Password1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel_Password)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                 

    private void cmbPermitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPermitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPermitActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String old = String.valueOf(txtCurrent.getPassword());
        String password1 = String.valueOf(txtPassword1.getPassword());
        String password2 = String.valueOf(txtPassword2.getPassword());
        if (!password1.equals(password2)) {
            JOptionPane.showMessageDialog(null, "Login failed", "Please review the password \n\" The account or password is incorrect \"", JOptionPane.INFORMATION_MESSAGE);
            txtPassword2.setText("");
            txtPassword1.setText("");
            return;
        }
        String permit = String.valueOf(Login.PermitionIndex + 1);
        AccountDAO dao = new AccountDAO() {};
        Boolean hasPermit = dao.hasRole(username, old, permit);
        if (!hasPermit) {
            JOptionPane.showMessageDialog(null, "Login failed", "Please review the password \n\" The account or password is incorrect \"", JOptionPane.INFORMATION_MESSAGE);
            txtPassword2.setText("");
            txtPassword1.setText("");
        } else {
            dao.updatePassword(username, old, permit, password1);
            if (Login.PermitionIndex == 0) {
          
                 JOptionPane.showMessageDialog(null, "Change success", "Please continue\n", JOptionPane.INFORMATION_MESSAGE);
                 this.setVisible(false);
                 java.awt.EventQueue.invokeLater(() -> {
                    new StudentPermittion().setVisible(true);
                });
            } else {
                
                JOptionPane.showMessageDialog(null, "Change success", "Please continue\n", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                java.awt.EventQueue.invokeLater(() -> {
                    new AdminPermittion().setVisible(true);
                });
            }
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if (Login.PermitionIndex == 0) {
            java.awt.EventQueue.invokeLater(() -> {
                new StudentPermittion().setVisible(true);
            });
        } else {
            java.awt.EventQueue.invokeLater(() -> {
                new AdminPermittion().setVisible(true);
            });
        }
        
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cmbPermit;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JLabel jlabel_Password;
    private javax.swing.JLabel jlabel_Password1;
    private javax.swing.JLabel jlabel_Password2;
    private javax.swing.JLabel jlabel_Password3;
    private javax.swing.JLabel jlabel_Username;
    private javax.swing.JLabel jlabel_Username1;
    private javax.swing.JPasswordField txtCurrent;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
